/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pfiches;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author quent
 */
public class FChoix extends javax.swing.JDialog {
    
    private  String DOSS_IMAGES = "src/pimages/" ;
    private boolean deuxJoueurs;
    private String nom1="";
    private String nom2="";
    private int modeJeu;
    private int nbrCases;
    private String nivOrdi=null;
    private boolean nouveau=true;
    /**
     * Creates new form FChoix
     */
    public FChoix(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(-10,0);
        this.setSize(1600,830);
        
        //Initialisation des images et de la visibilité des composants de l'interface graphique
        Toolkit t = Toolkit.getDefaultToolkit();
        Image img = t.getImage(DOSS_IMAGES+"basc_OUI.png");
        ((FAccueil) this.getParent()).afficher(img,bNouveau);
        
        lBackground.setSize(1550,817);
        Image img3 = t.getImage(DOSS_IMAGES+"Galaxio_Choix.png");
        ((FAccueil) this.getParent()).afficher(img3,lBackground);
        
        Image img4 = t.getImage(DOSS_IMAGES+"Charger_partie.png");
        ((FAccueil) this.getParent()).afficher(img4,lChargerPartie);
        
        Image img5 = t.getImage(DOSS_IMAGES+"Mode_Jeu.png");
        ((FAccueil) this.getParent()).afficher(img5,lModeJeu);
        
        Image img6 = t.getImage(DOSS_IMAGES+"Nom.png");
        ((FAccueil) this.getParent()).afficher(img6,lNom1);
        
        Image img8 = t.getImage(DOSS_IMAGES+"Deuxième_Nom.png");
        ((FAccueil) this.getParent()).afficher(img8,lNom2);
        
        Image img9 = t.getImage(DOSS_IMAGES+"Taille_Plateau.png");
        ((FAccueil) this.getParent()).afficher(img9,lPlateau);
        
        Image img11 = t.getImage(DOSS_IMAGES+"diffOrdi.png");
        ((FAccueil) this.getParent()).afficher(img11,lOrdi);
        
        Image img12 = t.getImage(DOSS_IMAGES+"Retour_Accueil .png");
        ((FAccueil) this.getParent()).afficher(img12,bAccueil);
        
        lNom1.setVisible(false);
        tfNom1.setVisible(false);
        lNom2.setVisible(false);
        tfNom2.setVisible(false);
        lPlateau.setVisible(false);
        cbPlateau.setVisible(false);
        bTerminer.setVisible(false);
        lOrdi.setVisible(false);
        cbOrdi.setVisible(false);
        bNouveau.setVisible(true);
        
        
        
        // Ferme le programme lorsqu'on appuie sur la croix
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                // Fermer complètement le programme lorsque la JDialog se ferme
                System.exit(0);
            }
        });
        
        //Utilisation d'un DocumentListener pour les TextFields afin de connaître leur valeur en temps réél
        tfNom1.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateTextField("nom1");
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateTextField("nom1");
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }
        });
        
        tfNom2.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateTextField("nom2");
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateTextField("nom2");
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }
        });
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pBascule = new javax.swing.JPanel();
        bNouveau = new javax.swing.JButton();
        lChargerPartie = new javax.swing.JLabel();
        pModeJeu = new javax.swing.JPanel();
        lModeJeu = new javax.swing.JLabel();
        cbModeJeu = new javax.swing.JComboBox<>();
        pNoms = new javax.swing.JPanel();
        lNom1 = new javax.swing.JLabel();
        tfNom1 = new javax.swing.JTextField();
        tfNom2 = new javax.swing.JTextField();
        lNom2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lOrdi = new javax.swing.JLabel();
        cbOrdi = new javax.swing.JComboBox<>();
        cbPlateau = new javax.swing.JComboBox<>();
        lPlateau = new javax.swing.JLabel();
        bAccueil = new javax.swing.JButton();
        bTerminer = new javax.swing.JButton();
        lBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1704, 943));
        getContentPane().setLayout(null);

        jPanel2.setOpaque(false);

        pBascule.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        pBascule.setForeground(new java.awt.Color(255, 255, 255));
        pBascule.setOpaque(false);

        bNouveau.setBorder(null);
        bNouveau.setBorderPainted(false);
        bNouveau.setContentAreaFilled(false);
        bNouveau.setFocusPainted(false);
        bNouveau.setPreferredSize(new java.awt.Dimension(70, 20));
        bNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNouveauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBasculeLayout = new javax.swing.GroupLayout(pBascule);
        pBascule.setLayout(pBasculeLayout);
        pBasculeLayout.setHorizontalGroup(
            pBasculeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBasculeLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(bNouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pBasculeLayout.setVerticalGroup(
            pBasculeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBasculeLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(bNouveau, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addComponent(lChargerPartie, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(pBascule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pBascule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lChargerPartie, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(160, 150, 890, 113);

        pModeJeu.setOpaque(false);

        lModeJeu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lModeJeu.setForeground(new java.awt.Color(255, 255, 255));

        cbModeJeu.setBackground(new java.awt.Color(255, 0, 255));
        cbModeJeu.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        cbModeJeu.setForeground(new java.awt.Color(255, 255, 255));
        cbModeJeu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir un Mode", "1 vs 1", "1 vs Ordi" }));
        cbModeJeu.setBorder(null);
        cbModeJeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbModeJeuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pModeJeuLayout = new javax.swing.GroupLayout(pModeJeu);
        pModeJeu.setLayout(pModeJeuLayout);
        pModeJeuLayout.setHorizontalGroup(
            pModeJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pModeJeuLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lModeJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbModeJeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        pModeJeuLayout.setVerticalGroup(
            pModeJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pModeJeuLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(pModeJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbModeJeu)
                    .addComponent(lModeJeu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(pModeJeu);
        pModeJeu.setBounds(300, 260, 820, 100);

        pNoms.setOpaque(false);
        pNoms.setLayout(null);

        lNom1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lNom1.setForeground(new java.awt.Color(255, 255, 255));
        pNoms.add(lNom1);
        lNom1.setBounds(400, 20, 350, 50);

        tfNom1.setBackground(new java.awt.Color(255, 0, 255));
        tfNom1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        tfNom1.setForeground(new java.awt.Color(255, 255, 255));
        tfNom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNom1ActionPerformed(evt);
            }
        });
        pNoms.add(tfNom1);
        tfNom1.setBounds(756, 20, 160, 54);

        tfNom2.setBackground(new java.awt.Color(255, 0, 255));
        tfNom2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        tfNom2.setForeground(new java.awt.Color(255, 255, 255));
        tfNom2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNom2ActionPerformed(evt);
            }
        });
        pNoms.add(tfNom2);
        tfNom2.setBounds(1290, 20, 156, 54);

        lNom2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lNom2.setForeground(new java.awt.Color(255, 255, 255));
        pNoms.add(lNom2);
        lNom2.setBounds(960, 10, 324, 81);

        getContentPane().add(pNoms);
        pNoms.setBounds(0, 380, 1920, 120);

        jPanel1.setOpaque(false);

        lOrdi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lOrdi.setForeground(new java.awt.Color(255, 255, 255));

        cbOrdi.setBackground(new java.awt.Color(255, 0, 255));
        cbOrdi.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        cbOrdi.setForeground(new java.awt.Color(255, 255, 255));
        cbOrdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Niveau Ordi", "Facile", "Moyen", "Difficile" }));
        cbOrdi.setBorder(null);
        cbOrdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOrdiActionPerformed(evt);
            }
        });

        cbPlateau.setBackground(new java.awt.Color(255, 0, 255));
        cbPlateau.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        cbPlateau.setForeground(new java.awt.Color(255, 255, 255));
        cbPlateau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir un Plateau", "3x3", "4x4", "5x5" }));
        cbPlateau.setBorder(null);
        cbPlateau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPlateauActionPerformed(evt);
            }
        });

        lPlateau.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lPlateau.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(lOrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(lPlateau, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbOrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPlateau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(449, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbOrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lOrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbPlateau, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lPlateau, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 510, 1320, 170);

        bAccueil.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bAccueil.setBorderPainted(false);
        bAccueil.setContentAreaFilled(false);
        bAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAccueilActionPerformed(evt);
            }
        });
        getContentPane().add(bAccueil);
        bAccueil.setBounds(10, 700, 178, 79);

        bTerminer.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bTerminer.setBorderPainted(false);
        bTerminer.setContentAreaFilled(false);
        bTerminer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTerminerActionPerformed(evt);
            }
        });
        getContentPane().add(bTerminer);
        bTerminer.setBounds(1220, 690, 208, 77);

        lBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pimages/Galaxio_Choix.png"))); // NOI18N
        lBackground.setPreferredSize(new java.awt.Dimension(1704, 943));
        getContentPane().add(lBackground);
        lBackground.setBounds(0, -20, 1960, 950);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbModeJeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbModeJeuActionPerformed
        // ComboBox afin de connaître le mode jeu souhaité. 
        String jeu = (String) cbModeJeu.getSelectedItem();
        Toolkit t = Toolkit.getDefaultToolkit();
        Image img; // t.getImage(DOSS_IMAGES+"basc_OUI.png");
        
        if(jeu.equals("1 vs 1")){   //Affichage des composants souhaités selon le mode de jeu
            modeJeu=0;
            img=t.getImage(DOSS_IMAGES+"Premier_Astronaute.png");   //Changement du nom du label pour le joueur selon le mode de jeu
            lNom1.setSize(324,81);
            ((FAccueil) this.getParent()).afficher(img,lNom1);
            tfNom1.setText(null);
            tfNom2.setText(null);
            lNom1.setVisible(true);
            tfNom1.setVisible(true);
            lNom2.setVisible(true);
            tfNom2.setVisible(true);
            deuxJoueurs=true;
            lOrdi.setVisible(false);
            cbOrdi.setVisible(false);
            cbPlateau.setSelectedItem("Choisir un Plateau");
            cbOrdi.setSelectedItem("Niveau Ordi");
        }else if(jeu.equals("1 vs Ordi")){  //Affichage des composants souhaités selon le mode de jeu
            modeJeu=1;
            img=t.getImage(DOSS_IMAGES+"Nom.png");  //Changement du nom du label pour le joueur selon le mode de jeu
            lNom1.setSize(350,50);
            ((FAccueil) this.getParent()).afficher(img,lNom1);
            tfNom1.setText(null);
            tfNom2.setText(null);
            nom2="";
            lNom1.setVisible(true);
            tfNom1.setVisible(true);
            lOrdi.setVisible(true);
            cbOrdi.setVisible(true);
            lNom2.setVisible(false);
            tfNom2.setVisible(false);
            deuxJoueurs=false;
        }else{  //On enlève les composants graphique si aucun mode de jeu n'a été sélectionné
            lNom1.setVisible(false);
            tfNom1.setVisible(false);
            lNom2.setVisible(false);
            tfNom2.setVisible(false);
            lPlateau.setVisible(false);
            cbPlateau.setVisible(false);
            lOrdi.setVisible(false);
            cbOrdi.setVisible(false);
            cbPlateau.setSelectedItem("Choisir un Plateau");
            cbOrdi.setSelectedItem("Niveau Ordi");
        }
    }//GEN-LAST:event_cbModeJeuActionPerformed

    private void cbPlateauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlateauActionPerformed
        // ComboBox permettant de choisir le type de plateau souhaité
        Toolkit t = Toolkit.getDefaultToolkit();
        String cases = (String) cbPlateau.getSelectedItem();
        bTerminer.setSize(208,77);
        if(cases.equals("3x3")){    //Modification 
            nbrCases=3;
            if(nouveau){    //Si une nouvelle partie est créée on change l'image du bouton par "créer", sinon par "charger"
                Image img10 = t.getImage(DOSS_IMAGES+"Creer.png");
                bTerminer.setSize(208,77);
                ((FAccueil) this.getParent()).afficher(img10,bTerminer);
            }else{
                Image img10 = t.getImage(DOSS_IMAGES+"Charger.png");
                bTerminer.setSize(208,77);
                ((FAccueil) this.getParent()).afficher(img10,bTerminer);
            }
        }else if(cases.equals("4x4")){
            nbrCases=4;
            if(nouveau){
                Image img10 = t.getImage(DOSS_IMAGES+"Creer.png");
                ((FAccueil) this.getParent()).afficher(img10,bTerminer);
            }else{
                Image img10 = t.getImage(DOSS_IMAGES+"Charger.png");
                ((FAccueil) this.getParent()).afficher(img10,bTerminer);
            }
        }else if(cases.equals("5x5")){
            nbrCases=5;
            if(nouveau){
                Image img10 = t.getImage(DOSS_IMAGES+"Creer.png");
                ((FAccueil) this.getParent()).afficher(img10,bTerminer);
            }else{
                Image img10 = t.getImage(DOSS_IMAGES+"Charger.png");
                ((FAccueil) this.getParent()).afficher(img10,bTerminer);
            }
        }else if(!nouveau){ //Affichage ou non du bouton bTerminer selon si on charge une partie ou non
            bTerminer.setVisible(true);
        }else{
            bTerminer.setVisible(false);
        }
    }//GEN-LAST:event_cbPlateauActionPerformed

    private void bTerminerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTerminerActionPerformed
        // Bouton permettant d'initialiser la fiche plateau et de  l'afficher
        FPlateau2 f = ((FAccueil) this.getParent()).getFichPlateau();
        this.setVisible(false);
        f.setVisible(true);
        
    }//GEN-LAST:event_bTerminerActionPerformed

    private void cbOrdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOrdiActionPerformed
        // ComboBox permettant de définir le niveau de l'ordinateur
        String niveau = (String) cbOrdi.getSelectedItem();
        if(niveau.equals("Facile")){
            nivOrdi="Facile";
        }else if(niveau.equals("Moyen")){
            nivOrdi="Moyen";
        }else if(niveau.equals("Difficile")){
            nivOrdi="Difficile";
        }else{
            nivOrdi=null;
            cbPlateau.setSelectedItem("Choisir un Plateau");
        }
        //Affichage des composants ou non selon les valeurs des TextFields et/ou du niveau de l'ordinateur
        if((deuxJoueurs==false && nom1.length()>0 && nivOrdi!=null)){
            lPlateau.setVisible(true);
            cbPlateau.setVisible(true);
        }else{
            lPlateau.setVisible(false);
            cbPlateau.setVisible(false);
            cbPlateau.setSelectedItem("Choisir un Plateau");
        }
    }//GEN-LAST:event_cbOrdiActionPerformed

    private void tfNom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNom1ActionPerformed

    private void tfNom2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNom2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNom2ActionPerformed

    private void bNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNouveauActionPerformed
        // Bouton permettant de choisir entre créer une nouvelle partie ou en charge une existente
        Toolkit t = Toolkit.getDefaultToolkit();
        //bNouveau.setSize(90,40);
        if(nouveau){    //Affichage des composants souhaités si on créé une partie
            Image img = t.getImage(DOSS_IMAGES+"basc_NON.png");
            bNouveau.setSize(90,40);
            ((FAccueil) this.getParent()).afficher(img,bNouveau);
            lNom1.setVisible(false);
            tfNom1.setVisible(false);
            lNom2.setVisible(false);
            tfNom2.setVisible(false);
            lPlateau.setVisible(false);
            cbPlateau.setVisible(false);
            lOrdi.setVisible(false);
            cbOrdi.setVisible(false);
            lModeJeu.setVisible(false);
            cbModeJeu.setVisible(false);
            nouveau=false;
            Image img10 = t.getImage(DOSS_IMAGES+"Charger.png");
            bTerminer.setSize(208,77);
            ((FAccueil) this.getParent()).afficher(img10,bTerminer);
            bTerminer.setVisible(true);
            
        }else{  //Affichage des composants souhaités si on charge une partie
            Image img = t.getImage(DOSS_IMAGES+"basc_OUI.png");
            //pBascule.setSize(93,43);
            bNouveau.setSize(90,40);
            ((FAccueil) this.getParent()).afficher(img,bNouveau);
            lNom1.setVisible(false);
            tfNom1.setVisible(false);
            lNom2.setVisible(false);
            tfNom2.setVisible(false);
            lPlateau.setVisible(false);
            cbPlateau.setVisible(false);
            lOrdi.setVisible(false);
            cbOrdi.setVisible(false);
            lModeJeu.setVisible(true);
            cbModeJeu.setVisible(true);
            nouveau=true;
            Image img10 = t.getImage(DOSS_IMAGES+"Creer.png");
            bTerminer.setSize(208,77);
            ((FAccueil) this.getParent()).afficher(img10,bTerminer);
            bTerminer.setVisible(false);
            
        }

    }//GEN-LAST:event_bNouveauActionPerformed

    private void bAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAccueilActionPerformed
        // Bouton permettant de revenir sur l'écran d'accueil
        ((FAccueil) this.getParent()).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bAccueilActionPerformed

    
    
    private void updateTextField(String nom) {
        // Récupérer le texte des TextFields en temps réél
        
        if(nom.equals("nom1")){
            
            nom1 = tfNom1.getText();
        }else{
            nom2 = tfNom2.getText();
        }
        //Affichage des composants souhaités ou non si les TextFields ne sont pas vides et/ou si le niveau de l'ordinateur n'est pas nul
        if((deuxJoueurs==false && nom1.length()>0 && nivOrdi!=null) || (deuxJoueurs==true && nom1.length()>0 && nom2.length()>0)){
            lPlateau.setVisible(true);
            cbPlateau.setVisible(true);
        }else{
            lPlateau.setVisible(false);
            cbPlateau.setVisible(false);
            bTerminer.setVisible(false);
            cbPlateau.setSelectedItem("Choisir un Plateau");
        }
        if(!nouveau){
            bTerminer.setVisible(true);
        }
        
    }
    
    
    
    //Méthode getter permettant de récupérer les données souhaitées pour créer ou charger une partie dans la fiche Plateau
    public boolean getNouveau(){
        return nouveau;
    }
    public int getModeJeu(){
        return modeJeu;
    }
    
    public String[] getNom(){
        String[] noms = {nom1,nom2};
        return noms;
    }
    
    public int getNbrCases(){
        return nbrCases;
    }
    
    public String getNiveauOrdi(){
        return nivOrdi;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FChoix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FChoix dialog = new FChoix(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAccueil;
    private javax.swing.JButton bNouveau;
    private javax.swing.JButton bTerminer;
    private javax.swing.JComboBox<String> cbModeJeu;
    private javax.swing.JComboBox<String> cbOrdi;
    private javax.swing.JComboBox<String> cbPlateau;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lBackground;
    private javax.swing.JLabel lChargerPartie;
    private javax.swing.JLabel lModeJeu;
    private javax.swing.JLabel lNom1;
    private javax.swing.JLabel lNom2;
    private javax.swing.JLabel lOrdi;
    private javax.swing.JLabel lPlateau;
    private javax.swing.JPanel pBascule;
    private javax.swing.JPanel pModeJeu;
    private javax.swing.JPanel pNoms;
    private javax.swing.JTextField tfNom1;
    private javax.swing.JTextField tfNom2;
    // End of variables declaration//GEN-END:variables
}
