/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pfiches;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import ptraitement.Joueur;

/**
 *
 * @author quent
 */
public class FVainqueur extends javax.swing.JDialog {
    private  String DOSS_IMAGES = "src/pimages/" ;
    /**
     * Creates new form FVainqueur
     */
    public FVainqueur(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Initialisation des images des composants dans l'interface graphique
        this.setLocation(-10,0);
        this.setSize(1600,830);
        lBackground.setSize(1550,795);
        Toolkit t = Toolkit.getDefaultToolkit();
        Image img=null;
        String vainqueur = ((FAccueil) this.getParent()).getGagnant();  //Récupération du nom du vainqueur depuis la variable gagnant de la classe mère
        if(vainqueur.equals("Ordi")){   //Affichage du vainqueur selon si c'est un ordinateur ou un joueur
            img = t.getImage(DOSS_IMAGES+"Gagner_Ordinateur.png");
        }else{
            img = t.getImage(DOSS_IMAGES+"Gagner.png");
            lEtoile.setText(vainqueur+"    !");
        }
        
        Image img2 = t.getImage(DOSS_IMAGES+"Retour_Accueil .png");
        ((FAccueil)this.getParent()).afficher(img2,bAccueil);
        ((FAccueil)this.getParent()).afficher(img,lBackground);
        
        // Ferme le programme lorsqu'on appuie sur la croix
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lEtoile = new javax.swing.JLabel();
        bAccueil = new javax.swing.JButton();
        lBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lEtoile.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 50)); // NOI18N
        lEtoile.setForeground(new java.awt.Color(255, 255, 255));
        lEtoile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lEtoile);
        lEtoile.setBounds(820, 270, 450, 60);

        bAccueil.setContentAreaFilled(false);
        bAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAccueilActionPerformed(evt);
            }
        });
        getContentPane().add(bAccueil);
        bAccueil.setBounds(10, 700, 178, 79);
        getContentPane().add(lBackground);
        lBackground.setBounds(0, 0, 1270, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAccueilActionPerformed
        // TODO add your handling code here:
        ((FAccueil) this.getParent()).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bAccueilActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FVainqueur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FVainqueur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FVainqueur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FVainqueur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FVainqueur dialog = new FVainqueur(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAccueil;
    private javax.swing.JLabel lBackground;
    private javax.swing.JLabel lEtoile;
    // End of variables declaration//GEN-END:variables
}
